export const EQUIPMENT_PRODUCTS = [
  {
    id: 1,
    name: "БЕГОВАЯ ДОРОЖКА PRORUN",
    price: 3200,
    image: "../img/treadmill1.webp",
    subcategory: "Тренажеры",
  },
  {
    id: 2,
    name: "ГАНТЕЛИ (НАБОР)",
    price: 150,
    image: "../img/dumbbells1.webp",
    subcategory: "Инвентарь",
  },
  {
    id: 3,
    name: "ГАНТЕЛИ (НАБОР) XL",
    price: 180,
    image: "../img/dumbbells2.webp",
    subcategory: "Инвентарь",
  },
  {
    id: 5,
    name: "ПРОТЕИН WHEY GOLD 1кг",
    price: 135,
    image: "../img/protein1.webp",
    subcategory: "Спорт. пит.",
  },
  {
    id: 6,
    name: "Креатин",
    price: 75,
    image: "../img/creatine1.jpg",
    subcategory: "Спорт. пит.",
  },
  {
    id: 7,
    name: "МУЛЬТИТРЕНАЖЕР EXPOGYM",
    price: 5700,
    image: "../img/treadmill2.webp",
    subcategory: "Тренажеры",
  },
  {
    id: 8,
    name: "ЭСПАНДЕР МУЛЬТИ",
    price: 275,
    image: "../img/expander.webp",
    subcategory: "Инвентарь",
  },
];

export const CLOTHES_PRODUCTS = [
  {
    id: 9,
    name: "JORDAN ESSENTIALS FLEECE",
    price: 300,
    image: "../img/pants1.jpg",
    subcategory: "Штаны",
  },
  {
    id: 10,
    name: "NIKE NOCTA FLEECE",
    price: 45,
    image: "../img/pants2.jpg",
    subcategory: "Штаны",
  },
  {
    id: 11,
    name: "JORDAN FLIGHT FLEECE",
    price: 45,
    image: "../img/pants3.webp",
    subcategory: "Штаны",
  },
  {
    id: 12,
    name: "Спортивные леггинсы",
    price: 45,
    image: "../img/pants4.webp",
    subcategory: "Штаны",
  },
  {
    id: 13,
    name: "Футболка DryFit",
    price: 30,
    image: "../img/t-shirt1.jpg",
    subcategory: "Футболки",
  },
  {
    id: 14,
    name: "Футболка DryFit",
    price: 30,
    image: "../img/t-shirt2.jpg",
    subcategory: "Футболки",
  },
  {
    id: 15,
    name: "Футболка DryFit",
    price: 30,
    image: "../img/t-shirt3.jpg",
    subcategory: "Футболки",
  },
  {
    id: 16,
    name: "Футболка DryFit",
    price: 30,
    image: "../img/t-shirt4.jpeg",
    subcategory: "Футболки",
  },
  {
    id: 17,
    name: "JORDAN JUMPMAN MVP 'Black/Anthracite' 10",
    price: 410,
    image: "../img/sneakers1.webp",
    subcategory: "Кроссовки",
  },
  {
    id: 18,
    name: "JORDAN 4 RETRO SE WET CEMENT",
    price: 420,
    image: "../img/sneakers2.jfif",
    subcategory: "Кроссовки",
  },
  {
    id: 19,
    name: "AIR JORDAN 5 RETRO SE UNC",
    price: 510,
    image: "../img/sneakers3.jpg",
    subcategory: "Кроссовки",
  },
  {
    id: 20,
    name: "AIR JORDAN 7 MVP",
    price: 110,
    image: "../img/sneakers4.webp",
    subcategory: "Кроссовки",
  },
  {
    id: 21,
    name: "JORDAN MONOGRAM DUFFLE BAG",
    price: 250,
    image: "../img/bag1.webp",
    subcategory: "Сумки",
  },
  {
    id: 22,
    name: "JORDAN AIR DUFFLE",
    price: 200,
    image: "../img/bag2.jpg",
    subcategory: "Сумки",
  },
  {
    id: 23,
    name: "PUMA PHASE 221L",
    price: 180,
    image: "../img/bag3.avif",
    subcategory: "Сумки",
  },
  {
    id: 24,
    name: "ADIDAS TR DUFFLE M",
    price: 280,
    image: "../img/bag4.webp",
    subcategory: "Сумки",
  },
  {
    id: 25,
    name: "ДЕТСКИЕ ПЕРЧАТКИ HARDCORE TRAINING EVOLUTION",
    price: 125,
    image: "../img/gloves1.png",
    subcategory: "Перчатки",
  },
  {
    id: 26,
    name: "БОКСЕРСКИЕ ПЕРЧАТКИ WINNING MS-300",
    price: 180,
    image: "../img/gloves2.png",
    subcategory: "Перчатки",
  },
  {
    id: 27,
    name: "БОКСЕРСКИЕ ПЕРЧАТКИ GRANT PROFESSIONAL",
    price: 210,
    image: "../img/gloves3.png",
    subcategory: "Перчатки",
  },
  {
    id: 28,
    name: "ТРЕНИРОВОЧНЫЕ ПЕРЧАТКИ CLETO REYES",
    price: 250,
    image: "../img/gloves4.png",
    subcategory: "Перчатки",
  },
  {
    id: 29,
    name: "JORDAN FLEECE",
    price: 155,
    image: "../img/shorts1.jpg",
    subcategory: "Шорты",
  },
  {
    id: 30,
    name: "JORDAN RUNNING TRAINING",
    price: 185,
    image: "../img/shorts2.jpeg",
    subcategory: "Шорты",
  },
  {
    id: 31,
    name: "ШОРТЫ ДЛЯ БЕГА PUMA",
    price: 155,
    image: "../img/shorts3.jpg",
    subcategory: "Шорты",
  },
  {
    id: 32,
    name: "ШОРТЫ ДЛЯ БЕГА Nike",
    price: 135,
    image: "../img/shorts4.jpg",
    subcategory: "Шорты",
  },
];

export const EQUIPMENT_SUBCATEGORIES = [
  "Все товары",
  "Тренажеры",
  "Инвентарь",
  "Спорт. пит.",
];

export const CLOTHES_SUBCATEGORIES = [
  "Все товары",
  "Кроссовки",
  "Сумки",
  "Перчатки",
  "Шорты",
  "Штаны",
  "Футболки",
];

export const CATEGORIES_DATA = {
  equipment: EQUIPMENT_PRODUCTS,
  clothes: CLOTHES_PRODUCTS,
};

export const SUBCATEGORIES_MAP = {
  equipment: EQUIPMENT_SUBCATEGORIES,
  clothes: CLOTHES_SUBCATEGORIES,
};
